services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: bantuexpress-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bantuexpress
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: bantuexpress_dev
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bantuexpress -d bantuexpress_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgis_data:
